# Generated by Django 5.0.2 on 2024-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
